### ISSUE TITLE
Version mismatch on awesome-wm

### ISSUE THREAD

**Issue by FreddyMaster** [RMTT/lua-pam#4]
I am getting a Lua core version mismatch.  It seems that the recent update to awesome-wm-git from the Arch User Repository which recently switched to lua version 504 has made this package incompatible with this package.
![image](https://user-images.githubusercontent.com/42700111/152590922-57a2e05f-1bcb-40e8-97b3-33e178ca2c37.png)
![image](https://user-images.githubusercontent.com/42700111/152591021-b9f8812c-3f14-478c-b784-e986d61754ea.png)

**Comment by RMTT** [comment]
I think you need reinstall `lua-pam`.

**Comment by INeido** [comment]
I am getting a very similar error:
`version mismatch: app. needs 504.0, Lua core provides 503.0`

I am using `lua-5.4.4-3` and `awesome-4.3-3`, so both should be up-to-date.
Is it a problem with my setup or with the module? I am not even sure what the numbers 503/504 are referring to...

**Comment by FreddyMaster** [comment]
> I am getting a very similar error: `version mismatch: app. needs 504.0, Lua core provides 503.0`
> 
> I am using `lua-5.4.4-3` and `awesome-4.3-3`, so both should be up-to-date. Is it a problem with my setup or with the module? I am not even sure what the numbers 503/504 are referring to...

check out my repo on gitlab on how i solved the issue.  I put the lua pam so file into my awesome wm folder
https://gitlab.com/FreddyMaster/dotfiles/-/commit/e3121231b6e9ffd9961c820b2064ca8c19619e70

**Comment by INeido** [comment]
What solved it for me was installing awesomewm-git and not awesomewm. Seems like the current stable version is only 503.

Now that both of us solved our issues, I think this can be closed.
